# Generated by Django 4.0.6 on 2022-07-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0002_rename_categoriepatient_categorie_categoriepatient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noms', models.CharField(max_length=150)),
                ('Date_naissance', models.DateField()),
                ('Adresse_physique', models.TextField()),
                ('Categorie_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categorie')),
                ('Etat_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivil')),
                ('Sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe')),
            ],
        ),
    ]
