# Generated by Django 4.0.6 on 2022-07-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noms', models.CharField(max_length=150)),
                ('Sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe')),
            ],
        ),
    ]
