# Generated by Django 4.0.6 on 2022-07-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0004_specialisation_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie_agent', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie_patient', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EtatcivilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etat_civil', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EtatcivilPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etat_civil', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=0, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commune', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='connexion',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='connexion',
            old_name='password',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='groupesanguin',
            name='groupesanguin',
        ),
        migrations.RemoveField(
            model_name='sexe',
            name='sexepatient',
        ),
        migrations.RemoveField(
            model_name='specialisation',
            name='specialisation',
        ),
        migrations.AddField(
            model_name='agent',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='agent',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.specialisation'),
        ),
        migrations.AddField(
            model_name='groupesanguin',
            name='Groupe_sanguin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='Profession',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sexe',
            name='Sexe_patient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='specialisation',
            name='Specialisation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Sexe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe'),
        ),
        migrations.AddField(
            model_name='agent',
            name='Categorie_Agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categorieagent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='etatcivil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilagent'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Commune',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cmmapp.localisation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Categorie_patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categoriepatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Etat_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilpatient'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='EtatCivil',
        ),
    ]
