# Generated by Django 4.0.6 on 2022-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0006_alter_patient_commune_alter_patient_etat_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieagent',
            name='Categorie_agent',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoriepatient',
            name='Categorie_patient',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='etatcivilagent',
            name='Etat_civil',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='etatcivilpatient',
            name='Etat_civil',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='groupesanguin',
            name='Groupe_sanguin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sexe',
            name='Sexe_patient',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='specialisation',
            name='Specialisation',
            field=models.CharField(max_length=150),
        ),
    ]
