# Generated by Django 4.0.6 on 2022-07-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0007_alter_categorieagent_categorie_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Categorie_patient',
            field=models.ForeignKey(default='LMC', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categoriepatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Commune',
            field=models.ForeignKey(default='Bandalungwa', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.localisation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Etat_civil',
            field=models.ForeignKey(default='Celibatiare', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilpatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sexe',
            field=models.ForeignKey(default='Feminin', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe'),
        ),
    ]
