# Generated by Django 4.0.6 on 2022-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0008_alter_patient_categorie_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Profession',
            field=models.CharField(max_length=150),
        ),
    ]
