# Generated by Django 4.0.6 on 2022-07-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0009_alter_patient_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Categorie_Agent',
            field=models.ForeignKey(default='LMC', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categorieagent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Sexe',
            field=models.ForeignKey(default='Feminin', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='etatcivil',
            field=models.ForeignKey(default='Celibataire', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilagent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialisation',
            field=models.ForeignKey(default='Encologiste', on_delete=django.db.models.deletion.CASCADE, to='cmmapp.specialisation'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='Commune',
            field=models.CharField(max_length=150),
        ),
    ]
