# Generated by Django 4.0.6 on 2022-07-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmmapp', '0010_alter_agent_categorie_agent_alter_agent_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Date_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Categorie_Agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categorieagent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='Sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='etatcivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilagent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.specialisation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Categorie_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.categoriepatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.localisation'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Etat_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.etatcivilpatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmapp.sexe'),
        ),
    ]
